// This file uses Node.js, which is the runtime for Netlify Functions

// You need to install the Google Gen AI SDK in your Netlify project:
// npm install @google/genai 

const { GoogleGenAI } = require("@google/genai");

// The Netlify function handler
exports.handler = async (event) => {
    // 1. Security Check: Only allow POST requests
    if (event.httpMethod !== 'POST') {
        return {
            statusCode: 405,
            body: JSON.stringify({ message: "Method Not Allowed. Use POST." }),
        };
    }

    // 2. Access the API Key securely from the Netlify environment variables
    const apiKey = process.env.GEMINI_API_KEY;

    if (!apiKey) {
        return {
            statusCode: 500,
            body: JSON.stringify({ message: "Server configuration error: GEMINI_API_KEY environment variable is not set." }),
        };
    }
    
    // Initialize the Google GenAI client
    const ai = new GoogleGenAI({ apiKey });

    try {
        // 3. Parse the request body from the client (index.html)
        const { chatHistory, systemPrompt } = JSON.parse(event.body);

        if (!chatHistory || !systemPrompt) {
            return {
                statusCode: 400,
                body: JSON.stringify({ message: "Missing required fields (chatHistory or systemPrompt) in the request body." }),
            };
        }

        // 4. Construct the Gemini API payload
        const generationConfig = {
            tools: [{ google_search: {} }], // Enable grounding for authoritative legal research
        };

        const response = await ai.models.generateContent({
            model: "gemini-2.5-flash-preview-09-2025",
            contents: chatHistory,
            config: generationConfig,
            systemInstruction: {
                parts: [{ text: systemPrompt }]
            }
        });

        // 5. Extract results and grounding information
        const candidate = response.candidates?.[0];
        let text = candidate?.content?.parts?.[0]?.text || "No response generated by the model.";
        let sources = [];
        
        const groundingMetadata = candidate?.groundingMetadata;
        if (groundingMetadata && groundingMetadata.groundingAttributions) {
            sources = groundingMetadata.groundingAttributions
                .map(attribution => ({
                    uri: attribution.web?.uri,
                    title: attribution.web?.title,
                }));
        }

        // 6. Return the secure result to the client
        return {
            statusCode: 200,
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ 
                text: text, 
                sources: sources 
            }),
        };

    } catch (error) {
        console.error("Gemini API Error in Netlify Function:", error.message);
        return {
            statusCode: 500,
            body: JSON.stringify({ message: "Failed to communicate with the Gemini API." }),
        };
    }
};